containerRegistryHost: crmibancodev001.azurecr.io
imageName: mibanco
imageTag: "2025_08_26_9"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

hpa:
  minReplicas: 2
  maxReplicas: 5
  target:
    cpu:
      UtilizationPercentage: 60
