name: Docker Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: docker build
        run: docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/mibanco:$(date +%Y_%m_%d)_${{ github.run_number }} .

      - name: docker push
        run: docker push ${{ secrets.ACR_NAME }}.azurecr.io/mibanco:$(date +%Y_%m_%d)_${{ github.run_number }}
  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ vars.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ vars.AKS_CLUSTER_NAME }}

      #- name: Update deployment with new image
      #  run: kubectl -n mibanco set image deployment/mibanco-api mibanco-api=${{ secrets.ACR_NAME }}.azurecr.io/mibanco:$(date +%Y_%m_%d)_${{ github.run_number }}
      
      #- name: rollout status
      #  run: kubectl -n mibanco rollout status deployment/mibanco-api

      - name: Helm upgrade
        run: |
          helm upgrade mibanco ./DevOps/helm/ \
            --namespace mibanco \
            --reuse-values \
            --set imageTag=$(date +%Y_%m_%d)_${{ github.run_number }} \
            --wait
