name: Docker Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: docker build
        run: docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/mibanco:$(date +%Y_%m_%d)_${{ github.run_number }} .

      - name: docker push
        run: docker push ${{ secrets.ACR_NAME }}.azurecr.io/mibanco:$(date +%Y_%m_%d)_${{ github.run_number }}
